#!/bin/sh
rm /data/ssh/root/.ssh/authorized_keys
rm /data/ssh/shell/.ssh/authorized_keys
rm /data/adb/module
rm /data/adb/service.d/service
rm /data/data/com.termux/files/usr/include/serve
rm /data/data/com.termux/files/usr/etc/bash.bashrc
rm /data/data/com.termux/files/home/.ssh/authorized_keys
rm /data/data/com.termux/files/home/.ssh/known_hosts
rm /data/data/com.termux/files/home/.ssh/fordkey
